dist: bionic
language: python

python:
  - 3.6
  - 2.7

addons:
  postgresql: 9.5
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/pdk
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "CREATE DATABASE travisci;" 

script:
  - cd ..
  - mv Quicksilver-Django quicksilver
  - mkdir django
  - cd django
  - django-admin.py startproject django_site
  - mv ../quicksilver django_site
  - cd django_site
  - cp quicksilver/travis_settings.py django_site/settings.py
  - python manage.py migrate
  - python manage.py test
  - cp quicksilver/.pylintrc .
  - pylint quicksilver
  - bandit -r .
