dist: trusty

env:

language: python

python:
  - 2.7

addons:
  postgresql: 9.5
  apt:
    packages:
    - spatialite-bin
    - postgresql-9.5-postgis-2.3
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/pdk
  
install:
  - pip install -r requirements.txt
  - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "CREATE DATABASE travisci;" 
  - psql -U postgres -c "CREATE EXTENSION postgis" -d travisci
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d travisci

script:
  - cd ..
  - mv Quicksilver-Django quicksilver
  - mkdir django
  - cd django
  - django-admin.py startproject django_site
  - mv ../quicksilver django_site
  - cd django_site
  - cp quicksilver/travis_settings.py django_site/settings.py
  - python manage.py migrate
  - python manage.py test
  - cp quicksilver/.pylintrc .
  - pylint quicksilver
  - bandit -r .
