# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True, max_length=1048576, null=True)),
                ('status', models.CharField(choices=[('success', 'Successful'), ('error', 'Error'), ('pending', 'Pending'), ('ongoing', 'Ongoing')], default='pending', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(db_index=True, max_length=4096)),
                ('arguments', models.TextField(max_length=1048576)),
                ('next_run', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='quicksilver.Task'),
        ),
    ]
