# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-15 20:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0002_auto_20200514_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
