# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-15 21:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0003_task_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='repeat_interval',
            field=models.IntegerField(default=0),
        ),
    ]
