# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0004_execution_repeat_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='repeat_interval',
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.IntegerField(default=0),
        ),
    ]
