# pylint: skip-file
# Generated by Django 2.2.16 on 2021-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0005_auto_20200515_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_module', 'Access Quicksilver components'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
