# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0007_auto_20210616_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
