# pylint: skip-file
# Generated by Django 2.2.24 on 2021-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0008_auto_20210921_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='postpone_alert_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
