# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0008_auto_20210921_1300'),
        ('quicksilver', '0011_auto_20210925_1317'),
    ]

    operations = [
    ]
