# pylint: skip-file
# Generated by Django 3.2.16 on 2022-10-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0014_alter_task_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arguments',
            field=models.TextField(blank=True, help_text='One argument per line', max_length=1048576, null=True),
        ),
    ]
