# pylint: skip-file
# Generated by Django 3.2.25 on 2024-07-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0016_auto_20230411_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('access_module', 'Access Quicksilver components'),)},
        ),
    ]
