# Generated by Django 4.2.13 on 2024-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0017_execution_total_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='total_runtime',
            field=models.FloatField(blank=True, null=True, verbose_name='runtime'),
        ),
    ]
