# pylint: skip-file
# Generated by Django 3.2.25 on 2024-07-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0017_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionsSupport',
        ),
    ]
