# pylint: skip-file
# Generated by Django 4.2.20 on 2025-04-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksilver', '0018_alter_execution_total_runtime'),
        ('quicksilver', '0018_delete_permissionssupport'),
    ]

    operations = [
    ]
