version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
      - build-38
      - build-27

jobs:
  build-38:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgres:9.6.9-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project quicksilver
            mkdir django
            cd django
            django-admin.py startproject qs
            mv ../quicksilver qs
            cd qs
            cp quicksilver/circle_settings.py qs/settings.py
            cp quicksilver/circle_urls.py qs/urls.py
            python manage.py migrate
            python manage.py test
            cp quicksilver/.pylintrc .
            pylint quicksilver
            bandit -r .      
      - save_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "/home/circleci/django/qs/quicksilver/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-27:
    docker:
      - image: cimg/python:2.7
      - image: circleci/postgres:9.6.9-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            virtualenv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project quicksilver
            mkdir django
            cd django
            django-admin.py startproject qs
            mv ../quicksilver qs
            cd qs
            cp quicksilver/circle_settings.py qs/settings.py
            cp quicksilver/circle_urls.py qs/urls.py
            python manage.py migrate
            python manage.py test
            cp quicksilver/.pylintrc .
            pylint quicksilver
            bandit -r .      
      - save_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "/home/circleci/django/qs/quicksilver/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app
